// Google Cloud
variable "gcp_audit_integration_name" {
    description = "The name of the GCP Audit integration in the Lacework console"
    type        = string
    default     = "lw-gcp-audit"
}

variable "gcp_audit_prefix" {
    description = "The prefix to use for every resource generated by this module"
    type        = string
    default     = "lw-gcp-tf"
}

variable "gcp_config_integration_name" {
    description = "The name of the GCP Config integration in the Lacework console"
    type        = string
    default     = "lw-gcp-config"
}

variable "gcp_org_integration" {
    description = "Set to true to integrate Lacework at the GCP Organization level"
    type        = bool
    default     = false
}
variable "gcp_organization_id" {
    description = "Organization ID (numeric) to integrate with"
    type        = number
    default     = null   
}

variable "gcp_project_id" {
    description = "Project for Lacework integration resources to reside in"
    type        = string
}

variable "gcp_region" {
    description = "Region to deploy GCP assets in"
    type        = string
    default     = "us-east1"
}
variable "gcp_zone" {
    description = "Default zone to use within gcp_region"
    type        = string
    default     = "us-east1-b"
}

// Lacework
variable "lacework_account" {
    description = "Lacework Account to integrate with"
    type        = string
}
variable "lacework_api_key" {
    description = "API Key to use for Lacework integrations"
    type        = string
    sensitive   = true
}
variable "lacework_api_secret" {
    description = "API Secret for lacework_api_key"
    type        = string
    sensitive   = true
}